### ISSUE TITLE
Create wiring diargram of hardware components

### ISSUE THREAD

**Issue by niecore** [JohannesHoffmann/herbiOS#5]
Hi Johannes,

Amazing Project!

Can you add more details on how to connect the heater to the arduino? 

Thanks!

**Comment by JohannesHoffmann** [comment]
Hi @niecore,

thank you very much. We are currently on a rewrite. The system will use mqtt as a main part for communication.
The wiring diagram is in the pipeline as well. I will focus on that the next couple of weeks. Join our discord server to get latest infos about the developing progress.

**Comment by niecore** [comment]
Great :)
